### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by CherbyMina** [nv95/Kotatsu#174] opened 2022-05-19 12:09 UTC
### Describe your suggested feature

Hello I'd like to request a feature where we can add another source by putting the link of it's site

Is it possible to add that?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/nv95/kotatsu-parsers/issues/new).
- [X] I have updated the app to version **[3.2.3](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment] 2022-05-19 13:28
> No, it's impossible, because every source has difficult parser algorithms
Duplicate of #12

**Closed** 2022-05-19 13:28 UTC
Labels: feature request
