### ISSUE TITLE
Где WebtoonRecyclerView?

### ISSUE THREAD

**Issue by ParTy-Play-go** [nv95/Kotatsu#80] opened 2021-12-24 17:35 UTC
Cannot access class 'WebtoonRecyclerView'. Check your module classpath for missing or conflicting dependencies
reader\ui\pager\webtoon\WebtoonReaderFragment.kt

**Comment by nv95** [comment] 2022-01-14 05:57
Duplicate of #79

**Closed by nv95** 2022-01-14 05:57 UTC
