### ISSUE TITLE
English manga sources

### ISSUE THREAD

**Issue by GoluLiliput** [nv95/Kotatsu#14] opened 2020-07-15 09:53 UTC
Is there any English manga sources in the app? I couldn't find any... Please help

**Comment by nv95** [comment] 2020-07-15 17:04
MangaTown is available for now

**Comment by JotaRodriguez4** [comment] 2021-05-20 06:33
Is there any Spanish manga sources in the app? I couldn't find any.
Some suggestions.
https://lectormanga.com/
https://lectortmo.com/
https://es.ninemanga.com/
Please help!

**Comment by ztimms73** [comment] 2021-05-20 15:35
> Is there any Spanish manga sources in the app? I couldn't find any.

No, there are no Spanish-language manga sources in the app, but I can try to add one of the suggested ones when I have free time.

**Comment by JotaRodriguez4** [comment] 2021-05-20 21:11
> > Is there any Spanish manga sources in the app? I couldn't find any.
> 
> No, there are no Spanish-language manga sources in the app, but I can try to add one of the suggested ones when I have free time.

Thank you!✨

**Comment by nv95** [comment] 2021-05-21 04:07
@ztimms73 looks like ninemanga.com has multiple languages, so, we can implement multiple sources with just different domains

**Comment by ztimms73** [comment] 2021-05-21 04:19
> @ztimms73 looks like ninemanga.com has multiple languages, so, we can implement multiple sources with just different domains.
> 
> upd: I will implement it

I had an idea to make the main English source, and in the domain settings, you could change it, for example, to es., ru., fr., etc.

**Comment by nv95** [comment] 2021-05-21 06:25
> in the domain settings

Users may not know about this feature. I think it will be better to create different sources with a single base implementation

**Comment by nv95** [comment] 2022-01-14 05:59
Closed as a duplicate of #77

**Closed by nv95** 2022-01-14 05:59 UTC
